#!/usr/bin/env bash
# create-project-backup-full.sh
#
# Creates a FULL project backup zip INCLUDING .git/ history (so the
# user has complete project provenance — every commit, every branch,
# every tag). Excludes only node_modules/ and .next/ (regenerable).
#
# Output: /home/z/my-project/download/aisalon-project-backup-FULL-<timestamp>.zip
#
# This is the "full version" the user requested alongside the slim
# `aisalon-project-backup-<ts>.zip` (which excludes .git).

set -euo pipefail

PROJECT_ROOT="/home/z/my-project"
DOWNLOAD_DIR="${PROJECT_ROOT}/download"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
ZIP_NAME="aisalon-project-backup-FULL-${TIMESTAMP}.zip"
ZIP_PATH="${DOWNLOAD_DIR}/${ZIP_NAME}"

mkdir -p "${DOWNLOAD_DIR}"

STAGE="$(mktemp -d)"
trap 'rm -rf "${STAGE}"' EXIT

echo "→ Staging project at ${STAGE}/aisalon-massapro (INCLUDING .git/) ..."

mkdir -p "${STAGE}/aisalon-massapro"
cd "${PROJECT_ROOT}"

# Copy EVERYTHING except the explicitly heavy / regenerable / private dirs.
# Note: .git/ IS included — that's the whole point of the "full" version.
rsync -a \
  --exclude='node_modules' \
  --exclude='.next' \
  --exclude='.turbo' \
  --exclude='.vercel' \
  --exclude='download' \
  --exclude='tool-results' \
  --exclude='backups' \
  --exclude='.env' \
  --exclude='*.log' \
  --exclude='.gdrive-token.json' \
  --exclude='.gcp-service-account.json' \
  ./ "${STAGE}/aisalon-massapro/"

# Generate the index for the full version.
cat > "${STAGE}/aisalon-massapro/PROJECT-INDEX.md" << 'INDEX_EOF'
# AI Salon Massapro — FULL Project Backup (with .git history)

> Generated by `scripts/create-project-backup-full.sh`. This is the
> FULL version — includes the `.git/` directory so you have complete
> commit history, every branch, every tag. Excludes only
> `node_modules/`, `.next/`, `.env` (regenerable / secret).
>
> For a slim version (no .git, faster to download), see
> `aisalon-project-backup-<ts>.zip`.

## Top-level layout

| Path | What it is |
|---|---|
| `.git/` | Full git history — every commit, branch, tag |
| `src/` | Next.js 15 app — pages, API routes, components, lib |
| `prisma/` | Prisma schema + migrations |
| `core/` | Team operating system — 9 named agents + 11-gate workflow + 3-tier task categories |
| `core/team/` | 9 agent job-description files (atlas, meridian, forge, lumen, canvas, sentinel, beacon, codex, aegis) |
| `core/tasks/` | Per-task folders with brief.md / implementation.md / CLOSED.md |
| `core/TASK_CATEGORIES.md` | SMALL / MID / HIGH tier definitions |
| `core/workflow.md` | 11-step task lifecycle (HIGH tier) |
| `core/README.md` | Team constitution v1.1 |
| `worklog.md` | Append-only multi-agent task log (3,000+ lines) |
| `public/` | Brand assets, images, PDFs |
| `scripts/` | Utility scripts (backup scripts, dev daemons) |
| `docs/` | CPO-PROTOCOL, PRODUCTION-ACTIVATION, runbooks |
| `preview/` | v3.0 plan execution docs (CI, ADRs, runbooks) |
| `mini-services/` | chat-service, quiz-service |
| `examples/` | websocket examples |
| `upload/` | User-uploaded reference images |
| `.env.example` | Template for env vars (real .env excluded for security) |
| `package.json` | Dependencies + scripts |
| `next.config.ts` | Next.js config |
| `tsconfig.json` | TypeScript config |
| `tailwind.config.ts` | Tailwind config |
| `vercel.json` | Vercel deployment config |

## How to restore

1. Unzip into a fresh directory.
2. `cp .env.example .env` and fill in real values (DB URL, NextAuth secret, OAuth secrets, etc.).
3. `npm install` (or `bun install`).
4. `npx prisma generate` + `npx prisma migrate deploy`.
5. `git log` to verify history is intact.
6. `npm run dev` to start the dev server.

## Chat logs

Raw chat logs live in the Z.ai gateway, not on disk. The conversation
is captured in:
- `worklog.md` (3,000+ lines, append-only)
- `core/tasks/<task-id>/brief.md` (per-task user request verbatim)
- `core/tasks/<task-id>/implementation.md` (per-task work log)

## Recent tasks (most recent first)

See `core/tasks/README.md` for the full closed-task table.
INDEX_EOF

echo "→ Zipping to ${ZIP_PATH} ..."
cd "${STAGE}"
zip -qr "${ZIP_PATH}" aisalon-massapro/

ZIP_SIZE=$(du -h "${ZIP_PATH}" | cut -f1)
ZIP_FILES=$(unzip -l "${ZIP_PATH}" | tail -1 | awk '{print $2}')
echo ""
echo "✓ FULL backup created."
echo "  Path:  ${ZIP_PATH}"
echo "  Size:  ${ZIP_SIZE}"
echo "  Files: ${ZIP_FILES}"
