#!/usr/bin/env bash
# create-project-backup.sh
#
# Creates a downloadable zip of the entire AI Salon project, organized
# for offline browsing / Google Drive upload. Excludes heavy dirs that
# can be regenerated (node_modules, .next, .git).
#
# Output: /home/z/my-project/download/aisalon-project-backup-<timestamp>.zip
#
# What's included:
#   - src/                  (all Next.js source code)
#   - prisma/               (schema + migrations)
#   - core/                 (team, tasks, workflow, categories — all .md)
#   - public/               (brand assets, images, PDFs — but NOT uploads dir)
#   - scripts/              (utility scripts)
#   - upload/               (user uploads — kept small)
#   - mini-services/        (chat-service, quiz-service)
#   - examples/             (websocket examples)
#   - preview/              (v3.0 plan execution docs)
#   - docs/                 (CPO-PROTOCOL, PRODUCTION-ACTIVATION, etc.)
#   - *.md, *.json, *.ts, *.mjs, *.yml  (root config files)
#   - .env.example          (NOT .env — secrets excluded)
#   - worklog.md
#   - core/tasks/           (all task folders with brief/impl/closed)
#   - PROJECT-INDEX.md      (generated — table of contents)
#
# What's EXCLUDED:
#   - node_modules/         (1.3 GB — regenerable via npm install)
#   - .next/                (build artifacts)
#   - .git/                 (255 MB — git history; ask if needed)
#   - .env                  (secrets — NEVER include)
#   - bun.lock, package-lock.json  (regenerable)

set -euo pipefail

PROJECT_ROOT="/home/z/my-project"
DOWNLOAD_DIR="${PROJECT_ROOT}/download"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
ZIP_NAME="aisalon-project-backup-${TIMESTAMP}.zip"
ZIP_PATH="${DOWNLOAD_DIR}/${ZIP_NAME}"

mkdir -p "${DOWNLOAD_DIR}"

# Stage files in a temp dir so we can add an index.md and a chat-log
# placeholder before zipping.
STAGE="$(mktemp -d)"
trap 'rm -rf "${STAGE}"' EXIT

echo "→ Staging project at ${STAGE}/aisalon-massapro ..."

# Copy the whole project, excluding heavy dirs.
mkdir -p "${STAGE}/aisalon-massapro"
cd "${PROJECT_ROOT}"

# Use rsync to exclude heavy/private dirs.
rsync -a \
  --exclude='node_modules' \
  --exclude='.next' \
  --exclude='.git' \
  --exclude='.env' \
  --exclude='.turbo' \
  --exclude='.vercel' \
  --exclude='download' \
  --exclude='tool-results' \
  --exclude='backups' \
  --exclude='*.log' \
  ./ "${STAGE}/aisalon-massapro/"

# Generate a project index so the user can navigate the zip.
cat > "${STAGE}/aisalon-massapro/PROJECT-INDEX.md" << 'INDEX_EOF'
# AI Salon Massapro — Project Backup Index

> Generated by `scripts/create-project-backup.sh`. This zip contains
> the full source code, the team operating system (`core/`), the
> worklog, and all task documentation. Excludes `node_modules/`,
> `.next/`, and `.git/` (regenerable / too heavy).

## Top-level layout

| Path | What it is |
|---|---|
| `src/` | Next.js 15 app — pages, API routes, components, lib |
| `prisma/` | Prisma schema + migrations |
| `core/` | Team operating system — 9 named agents + 11-gate workflow + 3-tier task categories |
| `core/team/` | 9 agent job-description files (atlas, meridian, forge, lumen, canvas, sentinel, beacon, codex, aegis) |
| `core/tasks/` | Per-task folders with brief.md / implementation.md / CLOSED.md |
| `core/TASK_CATEGORIES.md` | SMALL / MID / HIGH tier definitions |
| `core/workflow.md` | 11-step task lifecycle (HIGH tier) |
| `core/README.md` | Team constitution v1.1 |
| `worklog.md` | Append-only multi-agent task log (3,000+ lines) |
| `public/` | Brand assets, images, PDFs |
| `scripts/` | Utility scripts (this backup script, etc.) |
| `docs/` | CPO-PROTOCOL, PRODUCTION-ACTIVATION, runbooks |
| `preview/` | v3.0 plan execution docs (CI, ADRs, runbooks) |
| `mini-services/` | chat-service, quiz-service |
| `examples/` | websocket examples |
| `upload/` | User-uploaded reference images |
| `.env.example` | Template for env vars (real .env excluded) |
| `package.json` | Dependencies + scripts |
| `next.config.ts` | Next.js config |
| `tsconfig.json` | TypeScript config |
| `tailwind.config.ts` | Tailwind config |
| `vercel.json` | Vercel deployment config |

## How to restore

1. Unzip into a fresh directory.
2. `cp .env.example .env` and fill in real values.
3. `npm install` (or `bun install`).
4. `npx prisma generate` + `npx prisma migrate deploy`.
5. `npm run dev` to start the dev server.

## Chat logs

This backup does NOT include IM chat logs — those live in the Z.ai
gateway, not on disk. The conversation context is summarized in
`worklog.md` entries (which are written from the chat) and in
`core/tasks/<task-id>/brief.md` files (which quote the user's verbatim
request).

## Recent tasks (most recent first)

See `core/tasks/README.md` for the full closed-task table.
INDEX_EOF

# Add a note about chat logs being unavailable.
cat > "${STAGE}/aisalon-massapro/CHAT-LOGS-README.md" << 'CHAT_EOF'
# Chat Logs

The conversation between the user and Super Z (the main agent) is not
stored on disk — it lives in the Z.ai IM gateway. This backup does not
include the raw chat transcript.

What IS included that captures the conversation:

1. **`worklog.md`** (root) — append-only multi-agent task log. Every
   task entry includes the user's verbatim request (or a paraphrase)
   and a step-by-step work log. 3,000+ lines, covers every task back
   to 2026-06-22.

2. **`core/tasks/<task-id>/brief.md`** — per-task folder with the
   user's verbatim request quoted at the top, the category triage
   (SMALL/MID/HIGH), the restated goal, acceptance criteria, and
   closure notes.

3. **`core/tasks/<task-id>/implementation.md`** — what files were
   changed, what API routes were added, what Prisma schema changes
   were made, self-review notes, and the commit SHA.

4. **`core/tasks/<task-id>/CLOSED.md`** — closure summary.

If you need a verbatim chat transcript, you can:
- Scroll back in the Z.ai web UI (the conversation is preserved there).
- Or ask Super Z to dump the current conversation to a file (it can
  write a summary to `core/tasks/<task-id>/chat-transcript.md` on
  request).
CHAT_EOF

# Zip it up.
echo "→ Zipping to ${ZIP_PATH} ..."
cd "${STAGE}"
zip -qr "${ZIP_PATH}" aisalon-massapro/

# Report.
ZIP_SIZE=$(du -h "${ZIP_PATH}" | cut -f1)
ZIP_FILES=$(unzip -l "${ZIP_PATH}" | tail -1 | awk '{print $2}')
echo ""
echo "✓ Backup created."
echo "  Path:  ${ZIP_PATH}"
echo "  Size:  ${ZIP_SIZE}"
echo "  Files: ${ZIP_FILES}"
