#!/usr/bin/env bash
#
# Create the V3.1 milestone backup of the entire AI Salon Tel Aviv project.
#
# V3.1 = V3.0 + agenda thumbnail fix (1/N counter + slideshow-on-click)
#        + deployed to production at https://aisalon.massapro.com
#
# This backup is a MAIN MILESTONE: it captures the exact state of the
# codebase that is currently running in production, so it can be used
# as a rollback point if a future deploy breaks something.
#
# Includes (in addition to the source tree):
#   - prisma/             (DB schema + migrations)
#   - public/             (brand assets, favicons, uploaded images)
#   - docs/               (if present — runbooks, ADRs)
#   - scripts/            (all generation + ops scripts)
#   - download/           (prior backups + the V3.0 team plan docx)
#   - package.json + bun.lock + tsconfig.json + next.config.ts +
#     tailwind.config.ts + components.json + vercel.json + .env.example
#   - README.md + worklog.md (full project history)
#
# Excludes:
#   - node_modules/  (huge, regenerated by `bun install`)
#   - .next/         (build output, regenerated by `next build`)
#   - .vercel/       (Vercel CLI project link, machine-local)
#   - .git/          (version control history — separate concern)
#   - skills/        (skill files, not part of the app)
#   - upload/        (scratch uploads)
#   - db/            (SQLite DB file — too volatile, restore-from-prod instead)
#   - tool-results/  (transient tool output cache)
#
# Output: /home/z/my-project/download/aisalon-massapro-V3.1.tar.gz
#
set -euo pipefail

PROJECT_DIR="/home/z/my-project"
DOWNLOAD_DIR="${PROJECT_DIR}/download"
BACKUP_NAME="aisalon-massapro-V3.1"
OUT="${DOWNLOAD_DIR}/${BACKUP_NAME}.tar.gz"
MANIFEST="${DOWNLOAD_DIR}/${BACKUP_NAME}-MANIFEST.txt"

mkdir -p "${DOWNLOAD_DIR}"
rm -f "${OUT}" "${MANIFEST}"

# Use pbzip2 if available for faster compression, otherwise gzip.
if command -v pbzip2 >/dev/null 2>&1; then
  COMPRESS_FLAG="--use-compress-program=pbzip2"
else
  COMPRESS_FLAG="--gzip"
fi

echo "Creating V3.1 milestone backup at ${OUT}…"

cd "${PROJECT_DIR}"

# Build a manifest with provenance info — captured INSIDE the tarball
# so anyone restoring from it knows exactly what they're looking at.
cat > "${MANIFEST}" <<EOF
==============================================================
AI Salon Tel Aviv — MassaPro Platform
Milestone Backup: V3.1
==============================================================

Backup created:    $(date -u +"%Y-%m-%d %H:%M:%S UTC")
Created by:        Super Z (autonomous agent)
Machine:           $(hostname)
Project dir:       ${PROJECT_DIR}

Production URL:    https://aisalon.massapro.com
Vercel project ID: prj_aoKtARAel8wlmcIlLRjjSPKshMLA
Vercel team ID:    team_xQgfSmNbNo5JFCAaVyRboPBf
Git remote:        https://github.com/EzeCaz/aff-massapro.git
Git branch:        $(git rev-parse --abbrev-ref HEAD)
Git HEAD commit:   $(git rev-parse HEAD)
Git HEAD subject:  $(git log -1 --pretty=%s)

What's new in V3.1 (vs V3.0):
  - Agenda thumbnail fix: shows ONE picture with "1/N" counter in the
    top-right corner (was a single number before).
  - Clicking the agenda thumbnail opens the SpeakerSlideshowDialog
    with full reorder support (drag-and-drop via dnd-kit, persists
    via POST /api/images/reorder).
  - V3.0 deployed to production at https://aisalon.massapro.com
    (smoke-tested: /api/admin/members/companies returns 401, not 404).

V3.0 features also included (carried forward):
  - Email editor width fix
  - Click-to-edit on user lists
  - Edit button on tables
  - Company name combobox
  - Slideshow viewer with reorder (Photos tab)
  - CSV/XLS bulk import for Members + Registrants
    (/api/admin/{members,registrants}/bulk-import + import-template)

Rollback instructions:
  1. Untar this backup on a fresh machine:
       tar -xzf ${BACKUP_NAME}.tar.gz
  2. cd into the extracted directory
  3. bun install
  4. Set DATABASE_URL to point to the production Postgres (or a snapshot)
  5. bun run build
  6. vercel link --yes (re-link to the same project)
  7. vercel deploy --prod --yes

==============================================================
EOF

# Tar the source tree + manifest. The manifest is added at the root
# of the tarball so it's the first thing someone sees when extracting.
tar ${COMPRESS_FLAG} \
  --create \
  --file "${OUT}" \
  --exclude='node_modules' \
  --exclude='.next' \
  --exclude='.vercel' \
  --exclude='.git' \
  --exclude='skills' \
  --exclude='upload' \
  --exclude='db' \
  --exclude='tool-results' \
  --exclude='dev.log' \
  --exclude='*.log' \
  --exclude='.env.local' \
  --exclude='.env.prod' \
  --exclude='download' \
  --transform "s,^,${BACKUP_NAME}/," \
  "${MANIFEST#${PROJECT_DIR}/}" \
  .

# Show the final size + a file listing preview.
echo ""
echo "✓ Backup created: ${OUT}"
echo ""
echo "Size:"
du -h "${OUT}" | cut -f1
echo ""
echo "Top-level contents:"
tar --list --file "${OUT}" | head -30
echo "…"
echo ""
echo "Total files in backup:"
tar --list --file "${OUT}" | wc -l
echo ""
echo "Manifest:"
cat "${MANIFEST}"
