#!/usr/bin/env bash
#
# Create a V3.0 backup of the entire AI Salon Tel Aviv project.
#
# Excludes:
#   - node_modules/  (huge, regenerated by `npm install`)
#   - .next/         (build output, regenerated by `next build`)
#   - .vercel/       (Vercel CLI project link, regenerated on `vercel link`)
#   - dev.log        (dev server stdout)
#   - .git/          (version control history — would balloon the tarball)
#   - skills/        (skill files, not part of the app)
#   - upload/        (uploaded scratch files)
#   - db/            (the SQLite DB file — too volatile, excluded to
#                     avoid accidentally restoring a stale copy)
#   - tool-results/  (transient tool output cache)
#
# Output: /home/z/my-project/download/aisalon-massapro-V3.0.tar.gz
#
set -euo pipefail

PROJECT_DIR="/home/z/my-project"
DOWNLOAD_DIR="${PROJECT_DIR}/download"
BACKUP_NAME="aisalon-massapro-V3.0"
OUT="${DOWNLOAD_DIR}/${BACKUP_NAME}.tar.gz"

mkdir -p "${DOWNLOAD_DIR}"

# Remove any previous backup with the same name so we always get a
# clean file (the user explicitly asked for "V3.0").
rm -f "${OUT}"

# Use pbzip2 if available for faster compression, otherwise gzip.
if command -v pbzip2 >/dev/null 2>&1; then
  COMPRESS_FLAG="--use-compress-program=pbzip2"
else
  COMPRESS_FLAG="--gzip"
fi

echo "Creating V3.0 backup at ${OUT}…"

cd "${PROJECT_DIR}"

tar ${COMPRESS_FLAG} \
  --create \
  --file "${OUT}" \
  --exclude='node_modules' \
  --exclude='.next' \
  --exclude='.vercel' \
  --exclude='.git' \
  --exclude='skills' \
  --exclude='upload' \
  --exclude='db' \
  --exclude='tool-results' \
  --exclude='dev.log' \
  --exclude='*.log' \
  --exclude='.env.local' \
  --exclude='.env.prod' \
  --exclude='download' \
  --transform "s,^,${BACKUP_NAME}/," \
  .

# Show the final size + a file listing preview so the user can verify.
echo ""
echo "✓ Backup created: ${OUT}"
echo ""
echo "Size:"
du -h "${OUT}" | cut -f1
echo ""
echo "Top-level contents:"
tar --list --file "${OUT}" | head -30
echo "…"
echo ""
echo "Total files in backup:"
tar --list --file "${OUT}" | wc -l
