#!/usr/bin/env bash
#
# Create the V3.2 milestone backup of the entire AI Salon Tel Aviv project.
#
# V3.2 = V3.1 + email editor shrink-to-fit fix + RBAC role dropdown
#        in member editor (Admin / Co-host / Member) with Super Admin
#        hard-coded by email allowlist.
#
# This backup captures the EXACT state being deployed to production
# at https://aisalon.massapro.com, so it can be used as a rollback
# point if a future deploy breaks something.
#
# Includes (in addition to the source tree):
#   - prisma/             (DB schema + migrations)
#   - public/             (brand assets, favicons, uploaded images)
#   - scripts/            (all generation + ops scripts)
#   - package.json + bun.lock + tsconfig.json + next.config.ts +
#     tailwind.config.ts + components.json + vercel.json + .env.example
#   - README.md + worklog.md (full project history)
#
# Excludes:
#   - node_modules/  (huge, regenerated by `bun install`)
#   - .next/         (build output, regenerated by `next build`)
#   - .vercel/       (Vercel CLI project link, machine-local)
#   - .git/          (version control history — separate concern)
#   - skills/        (skill files, not part of the app)
#   - upload/        (scratch uploads)
#   - db/            (SQLite DB file — too volatile, restore-from-prod instead)
#   - tool-results/  (transient tool output cache)
#   - download/      (prior backups + deliverables — kept out of tarball)
#   - preview/       (V3.0 plan preview artifacts — not part of prod)
#
# Output: /home/z/my-project/download/aisalon-massapro-V3.2.tar.gz
#
set -euo pipefail

PROJECT_DIR="/home/z/my-project"
DOWNLOAD_DIR="${PROJECT_DIR}/download"
BACKUP_NAME="aisalon-massapro-V3.2"
OUT="${DOWNLOAD_DIR}/${BACKUP_NAME}.tar.gz"
MANIFEST="${DOWNLOAD_DIR}/${BACKUP_NAME}-MANIFEST.txt"

mkdir -p "${DOWNLOAD_DIR}"
rm -f "${OUT}" "${MANIFEST}"

# Use pbzip2 if available for faster compression, otherwise gzip.
if command -v pbzip2 >/dev/null 2>&1; then
  COMPRESS_FLAG="--use-compress-program=pbzip2"
else
  COMPRESS_FLAG="--gzip"
fi

echo "Creating V3.2 milestone backup at ${OUT}…"

cd "${PROJECT_DIR}"

# Build a manifest with provenance info — captured INSIDE the tarball
# so anyone restoring from it knows exactly what they're looking at.
cat > "${MANIFEST}" <<EOF
==============================================================
AI Salon Tel Aviv — MassaPro Platform
Milestone Backup: V3.2
==============================================================

Backup created:    $(date -u +"%Y-%m-%d %H:%M:%S UTC")
Created by:        Super Z (autonomous agent)
Machine:           $(hostname)
Project dir:       ${PROJECT_DIR}

Production URL:    https://aisalon.massapro.com
Vercel project ID: prj_aoKtARAel8wlmcIlLRjjSPKshMLA
Vercel team ID:    team_xQgfSmNbNo5JFCAaVyRboPBf
Git remote:        https://github.com/EzeCaz/aff-massapro.git
Git branch:        $(git rev-parse --abbrev-ref HEAD)
Git HEAD commit:   $(git rev-parse HEAD)
Git HEAD subject:  $(git log -1 --pretty=%s)

What's new in V3.2 (vs V3.1):
  - EMAIL EDITOR FIX: composer + template previews now shrink-to-fit
    inside the 600px container. Removed horizontal scrolling.
    CSS: overflow-hidden break-words + child constraints on img/table/pre/div
    via Tailwind arbitrary variants ([&_img]:max-w-full [&_table]:w-full etc).
    Affects src/app/admin/email/email-tab-client.tsx (2 preview instances).

  - RBAC ROLE DROPDOWN: in /admin → Edit Member dialog, Super Admins
    can now assign one of three roles via a "Role & permissions" section:
      * Admin        (bg #FF005A — pink badge)
      * Co-host      (bg #00E6FF/20 — teal badge)
      * Member       (no badge — clean UI)
    Super Admin status is HARD-CODED by email allowlist in
    src/lib/permissions.ts (SUPER_ADMIN_EMAILS = ["eze@massapro.com",
    "ezeszna@gmail.com"]) and cannot be granted via the UI.
    Self-demotion is blocked (client-side toast + server-side 403).
    Affects:
      - src/app/admin/admin-members-table.tsx (UI: dropdown + 4-color badges)
      - src/app/admin/page.tsx (passes currentUserEmail + currentUserRole)
      - src/lib/permissions.ts (ROLES, SUPER_ADMIN_EMAILS, helpers)
      - src/lib/auth-guards.ts (requireRole, requireSuperAdmin)
      - src/app/api/admin/members/[id]/route.ts (server-side RBAC enforcement)

V3.0 + V3.1 features also included (carried forward):
  - V3.1: Agenda thumbnail 1/N counter + click-to-open slideshow w/ dnd-kit reorder
  - V3.0: Email editor, click-to-edit, edit button, company combobox,
          slideshow viewer, CSV/XLS bulk import for Members + Registrants

Rollback instructions:
  1. Untar this backup on a fresh machine:
       tar -xzf ${BACKUP_NAME}.tar.gz
  2. cd into the extracted directory
  3. bun install
  4. Set DATABASE_URL to point to the production Postgres (or a snapshot)
  5. bun run build
  6. vercel link --yes (re-link to the same project)
  7. vercel deploy --prod --yes

==============================================================
EOF

# Tar the source tree + manifest. The manifest is added at the root
# of the tarball so it's the first thing someone sees when extracting.
tar ${COMPRESS_FLAG} \
  --create \
  --file "${OUT}" \
  --exclude='node_modules' \
  --exclude='.next' \
  --exclude='.vercel' \
  --exclude='.git' \
  --exclude='skills' \
  --exclude='upload' \
  --exclude='db' \
  --exclude='tool-results' \
  --exclude='dev.log' \
  --exclude='*.log' \
  --exclude='.env.local' \
  --exclude='.env.prod' \
  --exclude='download' \
  --exclude='preview' \
  --transform "s,^,${BACKUP_NAME}/," \
  "${MANIFEST#${PROJECT_DIR}/}" \
  .

# Show the final size + a file listing preview.
echo ""
echo "✓ Backup created: ${OUT}"
echo ""
echo "Size:"
du -h "${OUT}" | cut -f1
echo ""
echo "Top-level contents:"
tar --list --file "${OUT}" | head -30
echo "…"
echo ""
echo "Total files in backup:"
tar --list --file "${OUT}" | wc -l
echo ""
echo "Manifest:"
cat "${MANIFEST}"
